### ISSUE TITLE
Export does not include all notes

### ISSUE THREAD

**Issue by Keisir** [inkdropapp/inkdrop-export-as-markdown#6]
Hi, 
when exporting all notes or all notes of a notebook, some notes are not included. During export notes with status "dropped" or "completed" are ignored.
Even though notes with the status "dropped" or "completed" are not directly displayed in the note list within Inkdrop, nevertheless I think they should be considered during export.

**Comment by craftzdog** [comment]
Hi Keisir,

Thanks for the report. Agree, it currently does not export notes with the status "dropped" or "completed".
I'll be planning to fix it
